repository: zhui-zi/thelaststand
repository_url: https://github.com/zhui-zi/thelaststand

timezone: Asia/Shanghai
lang: zh_CN

title: 背水咖啡厅 · The Last Stand
alias_en: The Last Stand
alias_cn: 背水咖啡厅
description: A Navigation Website for FFXIVCN
keywords: 背水咖啡厅, The Last Stand, 最终幻想14, FF14, Final Fantasy XIV, 网址导航, 网站导航
url: https://ff14.cafe
established_at: "2022-01-01T00:00+08:00"

author: 坠子
author_url: https://www.zhuizi.me/
organization: 
organization_url: 
contact: contact[at]zhuizi[dot]me

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
